package targets

import "strings"

// generateCursorRules creates enhanced .cursorrules content for Cursor IDE.
func generateCursorRules() []byte {
	content := strings.Join([]string{
		"# Cursor Rules - OpenKit",
		"",
		"This project uses OpenKit for Spec-Driven Development.",
		"",
		"## Core Principles",
		"",
		"- Follow the SDD workflow: /specify → /clarify → /plan → /tasks → /impl → /test",
		"- Always read docs/requirements/ before making changes",
		"- Document decisions in docs/sprint/Sprint-XX/",
		"- Run verification scripts before committing",
		"",
		"## Project Structure",
		"",
		"- `docs/requirements/` - Feature specifications",
		"- `docs/sprint/` - Sprint planning and tasks",
		"- `.cursor/rules/` - Modular rules (see openkit.mdc)",
		"- `.cursor/skills/` - Reusable skills and patterns",
		"",
		"## Commands",
		"",
		"Run these before finalizing work:",
		"",
		"```bash",
		"# Run linters and type checks",
		"npm run lint",
		"",
		"# Run test suite",
		"npm test",
		"",
		"# Verify full build",
		"npm run build",
		"```",
		"",
		"## Skills",
		"",
		"Reference skills in `.cursor/skills/` for guidance on:",
		"- Clean code patterns",
		"- Testing strategies",
		"- API design",
		"- Security best practices",
		"",
		"For detailed rules, see `.cursor/rules/openkit.mdc`.",
		"",
	}, "\n")
	return []byte(content)
}

// generateCursorMDC creates a modular rule file for Cursor's .cursor/rules/ directory.
func generateCursorMDC() []byte {
	content := strings.Join([]string{
		"---",
		"name: OpenKit SDD Rules",
		"description: Spec-Driven Development workflow for OpenKit projects",
		"---",
		"",
		"# OpenKit SDD Rules",
		"",
		"## Workflow Overview",
		"",
		"This project follows Spec-Driven Development (SDD):",
		"",
		"1. **Specify** - Create feature spec in `docs/requirements/<feature>/`",
		"2. **Clarify** - Resolve ambiguities and edge cases",
		"3. **Plan** - Write implementation plan with tasks",
		"4. **Implement** - Execute tasks with verification steps",
		"5. **Test** - Run automated tests and manual checks",
		"",
		"## Before Writing Code",
		"",
		"- Check if a spec exists in `docs/requirements/`",
		"- If missing, create PROBLEM_STATEMENT.md, USER_STORIES.md, ACCEPTANCE_CRITERIA.md",
		"- Review RISKS.md for known issues",
		"- Read PLAN.md for implementation approach",
		"",
		"## During Implementation",
		"",
		"- Follow the task list in `docs/sprint/Sprint-XX/TASKS.md`",
		"- Mark tasks complete as you go",
		"- Run verification commands after each task",
		"- Update docs if behavior changes",
		"",
		"## Code Quality Standards",
		"",
		"### General",
		"",
		"- Functions should be < 20 lines when possible",
		"- Use descriptive names, avoid abbreviations",
		"- Prefer composition over inheritance",
		"- Write unit tests for business logic",
		"",
		"### Security",
		"",
		"- Never commit secrets or API keys",
		"- Validate all user inputs",
		"- Use parameterized queries for databases",
		"- Follow OWASP Top 10 guidelines",
		"",
		"### Testing",
		"",
		"- Write tests before fixing bugs (TDD for bug fixes)",
		"- Aim for 80%+ code coverage",
		"- Test edge cases and error conditions",
		"- Use descriptive test names",
		"",
		"## Verification Scripts",
		"",
		"Before committing, run:",
		"",
		"```bash",
		"# Lint check",
		"npm run lint",
		"",
		"# Type check",
		"npm run type-check",
		"",
		"# Run tests",
		"npm test",
		"",
		"# Build verification",
		"npm run build",
		"```",
		"",
		"## Skills Reference",
		"",
		"Consult `.cursor/skills/` for detailed guidance:",
		"",
		"- `clean-code/` - Code quality patterns",
		"- `testing-patterns/` - Test strategies",
		"- `api-patterns/` - API design principles",
		"- `database-design/` - Schema best practices",
		"- `security-fundamentals/` - Security guidelines",
		"",
		"## Documentation",
		"",
		"Keep these updated:",
		"",
		"- `docs/requirements/<feature>/` - Feature specs",
		"- `docs/sprint/Sprint-XX/TASKS.md` - Task progress",
		"- `README.md` - High-level overview",
		"- Inline code comments for complex logic",
		"",
	}, "\n")
	return []byte(content)
}
